name: ctview
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.11.*
  - pip
  - conda-forge:pdal>=2.8
  - conda-forge:python-pdal>=3.4
  - gdal>=3.9  # To get the "nearest" interpolation option for FillNoData
  - laspy
  - numpy
  - rasterio
  - pytest
  - pytest-cov==3.0.*
  - tqdm
  - black # reformat file
  - flake8
  - isort
  - pre-commit
  - hydra-core==1.3.*
  - fiona
  - ipython

  - pip:
    - ign-las-digital-models==2.0.0  # after name change
    - ign-pdal-tools>=1.11.1