name: ctview
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.9.*
  - pip
  - conda-forge:pdal==2.5.*
  - conda-forge:python-pdal==3.2.*
  - gdal
  - laspy
  - numpy
  - rasterio
  - pytest==6.2.*  # tests
  - pytest-cov==3.0.*
  - tqdm
  - black # reformat file
  - hydra-core==1.2.* # mnx config
  - hydra-colorlog==1.2.* # mnx config
  - fiona # mnx

  - pip:
    - --extra-index-url=https://nexus.ign.fr/repository/pypi-lidarhd-hosted/simple
    - -r requirements.txt