name: ctview
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.9.*
  - pip
  - conda-forge:pdal==2.3.*
  - conda-forge:python-pdal==3.0.*
  - gdal
  - laspy
  - geojson

  - pandas
  - opencv
  - numpy

  - geopandas
  - scipy
  - cgal
  - rasterio

  - pytest==6.2.*  # tests
  - pytest-cov==3.0.*

  - tqdm

  - black # reformat file

  # - pyproj
  # - pysimplegui

  # - pyshp
  # - psycopg2
  # - python-pdal
  # - requests
  # - pytest
  # - pytest-dependency
  
  # - isort
  # - fiona
  # - filelock

  - pip:
    - --extra-index-url=https://qlf-nexus.ign.fr/repository/pypi-lidarhd-hosted/simple
    - ign-gpao-project-builder
    - ign-gpao-client
    - ign-lidarutils
    - startinpy