# @package _global_

# path to original working directory
# hydra hijacks working directory by changing it to the current log directory,
# so it's useful to have this path as a special variable
# learn more here: https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
work_dir: ${hydra:runtime.cwd}

io:
  input_filename: null
  input_dir: null
  output_dir: null
  spatial_reference: EPSG:2154
  lut_folder: LUT
  extension: .tif
  raster_driver: GTiff
  no_data_value: -9999
  tile_geometry:
    tile_coord_scale: 1000  # meters
    tile_width: 1000  # meters

buffer:
  size: 100  # meters
  output_subdir: null  # exemple: "tmp/buffer"

density:
  pixel_size: 5  # meters
  keep_classes: [2, 66]  # 1 band with this classes
  lut_filename: LUT_DENSITY.txt
  output_subdir: DENS_FINAL
  intermediate_dirs:  # for each intermediate_dirs, if null the folder is not created
    density_values: null  # example: tmp/DENS_VAL

class_map:
  pixel_size: 0.5  # meters
  dxm_filter:  # filter used to generate dsm, the dsm is used to generate hillshade
    dimension: Classification
    keep_values: [1, 2, 3, 4, 5, 6, 9, 17, 64, 65, 66, 67, 202]
  lut_filename: LUT_CLASS.txt
  output_subdir: CLASS_FINAL
  hillshade_calc: "254*((A*(0.5*(B/255)+0.25))>254)+(A*(0.5*(B/255)+0.25))*((A*(0.5*(B/255)+0.25))<=254)"
  intermediate_dirs:  # for each intermediate_dirs, if null the folder is not created
    CC_raw: null  # exemple: CC_1_raw
    CC_raw_color: null  # exemple: CC_2_bcolor
    CC_fillgap: null  # exemple: CC_3_fg
    CC_fillgap_color: null  # exemple: CC_4_fgcolor
    CC_crop: null  # exemple: CC_5_crop
    dxm_raw: null  # exemple: "DSM_VAL"
    dxm_hillshade: null  # exemple: "tmp_dsm/hillshade"

hydra:
  output_subdir: null
  run:
    dir: .
