# @package _global_

# path to original working directory
# hydra hijacks working directory by changing it to the current log directory,
# so it's useful to have this path as a special variable
# learn more here: https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
work_dir: ${hydra:runtime.cwd}

io:
  input_filename: null
  input_dir: null
  output_dir: null
  spatial_reference: EPSG:2154
  lut_folder: LUT

tile_geometry:
  tile_coord_scale: 1000
  tile_width: 1000
  no_data_value: -9999

buffer:
  size: 100
  output_dir: "tmp/buffer"

density:
  pixel_size: 5
  keep_classes: [2, 66]
  extension: .tif
  dxm_interpolation: pdal-tin
  lut_filename: LUT_DENSITY.txt
  output_dir: DENS_FINAL
  intermediate_dirs:
    density_values: DENS_VAL
    density_color: DENS_COLOR
    dxm_raw: DTM_DENS
    dxm_hillshade: "tmp_dtm_dens/hillshade"

dtm:
  pixel_size: 1
  keep_classes: [2, 66]
  interpolation: pdal-tin
  extension: .tif
  color:
    cycles_DTM_colored: [1]
    folder_LUT: "LUT"
  output_dir: "DTM/color"
  intermediate_dirs:
    dxm_raw: "DTM"
    dxm_hillshade: "tmp_dtm/hillshade"

class_map:
  pixel_size: 0.5
  extension: .tif
  dxm_interpolation: pdal-tin
  keep_classes: [1, 2, 3, 4, 5, 6, 9, 17, 64, 65, 66, 67, 202]
  lut_filename: LUT_CLASS.txt
  output_dir: CC_5_fusion
  intermediate_dirs:
    CC_brut: CC_1_brut
    CC_brut_color: CC_2_bcolor
    CC_fillgap: CC_3_fg
    CC_fillgap_color: CC_4_fgcolor
    dxm_raw: "DSM"
    dxm_hillshade: "tmp_dsm/hillshade"

hydra:
  output_subdir: null
  run:
    dir: .
