# @package _global_

# path to original working directory
# hydra hijacks working directory by changing it to the current log directory,
# so it's useful to have this path as a special variable
# learn more here: https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
work_dir: ${hydra:runtime.cwd}

io:
  input_filename: null
  input_dir: null
  output_dir: null
  projection_epsg: 2154
  no_data_value: -9999
  extension: .tif
  raster_driver: "GTiff"

tile_geometry:
  tile_coord_scale: 1000  # meters
  tile_size: 1000  # meters

buffer:
  buffer_size: 100  # meters
  output_subdir: null  # exemple: "tmp/buffer"

density:
  pixel_size: 1  # meters
  keep_classes:
    - [2]  # band 1 (red)
    - [3, 4, 5, 6, 17]  # band 2 (green)

class_map:
  pixel_size: 1
  CBI_rules:
    - {"CBI": [5,6],"AGGREG": 56}
    - {"CBI": [5,17],"AGGREG": 57}
    - {"CBI": [2,6],"AGGREG": 26}
  precedence_classes: [56,26,6,17,5,57,2]
  intermediate_dirs:  # pour chaque intermediate_dirs, si null, le dossier n'est pas créé
    class_binary: null  # exemple: tmp/binary
    class_precedence: null
  colormap:
    - {value: 0, description: NODATA, color: [0, 0, 0]}
    - {value: 1, description: Defaut, color: [150, 150, 150]}
    - {value: 2, description: Sol, color: [207, 150, 70]}
    - {value: 3, description: Vegetation basse, color: [90, 110, 40]}
    - {value: 4, description: Vegetation intermediaire, color: [70, 150, 60]}
    - {value: 5, description: Vegetation haute, color: [70, 150, 60]}
    - {value: 6, description: Batiment, color: [180, 20, 20]}
    - {value: 9, description: Eau, color: [40, 140, 140]}
    - {value: 17, description: Pont, color: [85, 97, 137]}
    - {value: 64, description: Sursol perenne, color: [255, 0, 255]}
    - {value: 65, description: Artefact, color: [64, 0, 128]}
    - {value: 66, description: Point virtuel, color: [128, 0, 64]}
    - {value: 67, description: DiversBatiment, color: [180, 20, 20]}
    - {value: 56, description: BatiSurVeg, color: [180, 20, 20]}  # value = 70 (changé arbitrairement pour test)
    - {value: 26, description: PontSurVeg, color: [85, 97, 137]}   # value = 71 (changé arbitrairement pour test)
    - {value: 80, description: VegsurBati, color: [70, 150, 60]}
    - {value: 57, description: PontsurBati, color: [85, 97, 137]} # value = 81 (changé arbitrairement pour test)
    - {value: 89, description: DefsurBati, color: [180, 20, 20]}
    - {value: 90, description: VegsurPont, color: [70, 150, 60]}
    - {value: 91, description: BatisurPont, color: [180, 20, 20]}
    - {value: 99, description: DefsurPont, color: [150, 150, 150]}
    - {value: 214, description: Incertains batiment, color: [180, 20, 20]}
    - {value: 202, description: DiversBatiment_temp, color: [180, 20, 20]}


hydra:
  output_subdir: null
  run:
    dir: .
