# @package _global_

# path to original working directory
# hydra hijacks working directory by changing it to the current log directory,
# so it's useful to have this path as a special variable
# learn more here: https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
work_dir: ${hydra:runtime.cwd}

io:
  input_filename: null
  input_dir: null
  output_dir: null
  spatial_reference: EPSG:2154
  extension: .tif
  raster_driver: GTiff
  no_data_value: -9999
  tile_geometry:
    tile_coord_scale: 1000  # meters
    tile_width: 1000  # meters

buffer:
  size: 100  # meters
  output_subdir: null  # exemple: "tmp/buffer"

density:
  pixel_size: 5  # meters
  keep_classes:
    - [2, 66]  # 1 band with this classes
  colorize: True
  colormap:
  - {value: 0, color: [0, 0, 0]}
  - {value: 1, color: [20, 25, 255]}
  - {value: 2, color: [215, 25, 255]}
  - {value: 5, color: [215, 25, 28]}
  - {value: 6, color: [253, 173, 97]}
  - {value: 8, color: [255, 255, 192]}
  - {value: 9, color: [166, 217, 106]}
  - {value: 10, color: [26, 150, 65]}
  - {value: 300, color: [26, 150, 65]}
  output_subdir: DENS_FINAL
  intermediate_dirs:  # for each intermediate_dirs, if null the folder is not created
    density_values: null  # example: tmp/DENS_VAL

class_map:
  output_class_subdir: null  # Single band class map with colormap as metadata
  output_class_pretty_subdir: "CLASS_FINAL" # 3-bands colored class map
  pixel_size: 0.5  # meters
  CBI_rules: []  # No precedence
  precedence_classes: [1, 2, 3, 4, 5, 6, 9, 17, 64, 65, 66, 67, 202]  # default order with no precedence (to be updated)
  ignored_classes: []
  intermediate_dirs:  # for each intermediate_dirs, if null the folder is not created
    class_binary: null  # example: tmp/binary
  colormap:
  - {value: 0, description: "NODATA", color: [0, 0, 0]}
  - {value: 1, description: "Non classes", color: [255, 255, 255]}
  - {value: 2, description: "Sol", color: [255, 128, 0]}
  - {value: 3, description: "Vegetation basse", color: [0, 255, 0]}
  - {value: 4, description: "Vegetation intermediaire", color: [0, 255, 0]}
  - {value: 5, description: "Vegetation haute", color: [0, 255, 0]}
  - {value: 6, description: "Batiment", color: [255, 0, 0]}
  - {value: 9, description: "Eau", color: [0, 255, 255]}
  - {value: 17, description: "Pont", color: [255, 255, 0]}
  - {value: 64, description: "Sursol perenne", color: [128, 0, 64]}
  - {value: 65, description: "Artefact", color: [64, 0, 128]}
  - {value: 66, description: "Point virtuel", color: [255, 0, 255]}
  - {value: 67, description: "Divers Batiment", color: [255, 128, 128]}
  - {value: 202, description: "Candidats Batiment", color: [255, 128, 128]}
  dxm_filter:
    dimension: dsm_marker
    keep_values: [1]
  post_processing:
      fillnodata:
        apply: true
        max_distance: 2
        smoothing_iterations: 0
      smoothing: # The smoothing method uses GdalSieveFilter
        apply: false
        nconnectedness: 4 # indicating that diagonal pixels are considered directly adjacent or not. 4 no, 8 yes
        threshold : 12 # raster polygons with smaller pixel size of threshold will be merged into their largest neighbor
  # A: classification raster before hillshade
  # B: hillshade DSM
  hillshade_calc: "254*((A*(0.5*(B/255)+0.25))>254)+(A*(0.5*(B/255)+0.25))*((A*(0.5*(B/255)+0.25))<=254)"

hydra:
  output_subdir: null
  run:
    dir: .
